name: User Docker Image CI

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
    paths:
      - ".github/workflows/docker-image-user.yml"
      - "backend/go.mod"
      - "backend/go.sum"
      - "backend/scripts/**"
      - "backend/proto/**"
      - "backend/internal/**"
      - "backend/user/**"
      - ".containerignore"
      - "Dockerfile"
      - "!**.md"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/docker-image-user.yml"
      - "backend/go.mod"
      - "backend/go.sum"
      - "backend/scripts/**"
      - "backend/proto/**"
      - "backend/internal/**"
      - "backend/user/**"
      - ".containerignore"
      - "Dockerfile"
      - "!**.md"

jobs:
  build-images:
    name: Build User Docker images
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/urls-user
            ghcr.io/${{ github.repository_owner }}/urls-user

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfiles/Dockerfile-user
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
